// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgHhDu8txX26T8p4NkSg0R5UePxuOGbls',
    appId: '1:698103285003:web:c69a67da6780467d7c4e0e',
    messagingSenderId: '698103285003',
    projectId: 'ask-the-stoics',
    authDomain: 'ask-the-stoics.firebaseapp.com',
    storageBucket: 'ask-the-stoics.firebasestorage.app',
    measurementId: 'G-0NKV0W0TGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4XZc56OdiiMS6xuNXT7hX7X7wStCT1jA',
    appId: '1:698103285003:android:9d195cf846323aab7c4e0e',
    messagingSenderId: '698103285003',
    projectId: 'ask-the-stoics',
    storageBucket: 'ask-the-stoics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7nj2MPbvaCWuANjfhH5hdJ-JpO_rXGgw',
    appId: '1:698103285003:ios:b5a32fec9379ea2f7c4e0e',
    messagingSenderId: '698103285003',
    projectId: 'ask-the-stoics',
    storageBucket: 'ask-the-stoics.firebasestorage.app',
    iosBundleId: 'com.askthestoics.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7nj2MPbvaCWuANjfhH5hdJ-JpO_rXGgw',
    appId: '1:698103285003:ios:20ef193c2ce36bde7c4e0e',
    messagingSenderId: '698103285003',
    projectId: 'ask-the-stoics',
    storageBucket: 'ask-the-stoics.firebasestorage.app',
    iosBundleId: 'com.example.nickMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgHhDu8txX26T8p4NkSg0R5UePxuOGbls',
    appId: '1:698103285003:web:f5568a3a3f18775c7c4e0e',
    messagingSenderId: '698103285003',
    projectId: 'ask-the-stoics',
    authDomain: 'ask-the-stoics.firebaseapp.com',
    storageBucket: 'ask-the-stoics.firebasestorage.app',
    measurementId: 'G-FD1ZXS0EYW',
  );
}
